### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by malcb** [djinteractive/NetflixUK.bundle#1]
Hi,

I can't seem to get this to work and I wondered if it was a still working or whether netflix had changed and broken this?

TIA

**Comment by djinteractive** [comment]
Unfortunately I've not had time to test this on the new Server / Home Theater infrastructure, being on the other side of the world doesn't help when working with a service that utilises geo-ip blocking. I'm aware of some issues when the plugin is used on Windows Server, and unfortunately there is nothing I can do to within the channel plugin to resolve it, this is partly why the original netflix plugin was pulled from the channel listings a few months ago, that said I've not checked back there recently. If I get some time I'll spin up a server on AWS and see what I can do.

**Comment by malcb** [comment]
I've read that the latest PMS dropped webkit so no service that needs silverlight will work, dunno if that is correct.  I've backtracked to 0.9.7.22 (.28 had a bug with RMTP I believe).  I've had the standard netflix plugin working (on uk sub) but only for a few minutes and not well enough to give acceptable picture.  The client end is a now tv (roku) box.

**Comment by jbrines** [comment]
Did you guys ever get Netflix to work with Plex?

**Comment by djinteractive** [comment]
> Did you guys **ever** get Netflix to work with Plex?

Yes

Now if you asked "Does this plugin currently work with Plex?", then I would have to say no. Unfortunately the primary dependency and only means of playing back the video stream, Webkit, has been removed from Plex Media Server. It's also worth noting that Netflix are removing access to their public API in November, whilst we get the data from an alternative source, we do use their API to authenticate the user and access the Player API. Whilst we can potentially work around the API issues, we already do this to provide access to the UK region data, we would still need to find an alternative means to playback the video stream that works on all platforms.
